// commands/ai/ai.js - AI Commands with OpenAI Integration

import axios from 'axios';
// Configuration - Hardcoded API key (NOT RECOMMENDED for production)
const OPENAI_API_KEY = 'api';
const OPENAI_API_URL = 'https://api.openai.com/v1/chat/completions';

// ChatGPT command
export const chatgpt = {
    name: 'chatgpt',
    aliases: ['gpt', 'ai', 'chat'],
    category: 'ai',
    description: 'Chat with AI',
    execute: async (sock, m, args) => {
        if (!args[0]) return m.reply('❌ Please provide a prompt!\n\nExample: .chatgpt What is artificial intelligence?');
        
        try {
            const prompt = args.join(' ');
            m.reply('🤖 AI is thinking...');
            
            const response = await getChatGPTResponse(prompt);
            
            const aiText = `*🤖 CIARA-IV AI RESPONSE*\n\n*Prompt:* ${prompt}\n\n*Response:*\n${response}\n\n_Powered by OpenAI GPT_`;
            
            await sock.sendMessage(m.chat, { text: aiText }, { quoted: m });
            
        } catch (error) {
            console.error('ChatGPT Error:', error.response?.data || error.message);
            m.reply('❌ AI service is currently unavailable. Please try again later.');
        }
    }
};

// CIARA AI toggle command
export const ciara_ai = {
    name: 'ciara_ai',
    category: 'ai',
    description: 'Enable CIARA AI auto-responses',
    execute: async (sock, m) => {
        if (!global.db.settings.aimode) {
            global.db.settings.aimode = true;
            
            const welcomeText = `*🤖 CIARA-IV AI ACTIVATED* ✨\n\nHello! I'm CIARA-IV, your intelligent WhatsApp assistant created by CraigeeX🫟.\n\n*🎯 What I can do:*\n• Answer questions intelligently\n• Help with various tasks\n• Provide information and explanations\n• Engage in meaningful conversations\n• Assist with creative writing\n\n*💡 How to interact:*\n• Mention "ciara" in your message\n• Tag me directly (@bot)\n• Start conversations naturally\n\n*ℹ️ About my creator:*\nCraigeeX is a 19-year-old tech enthusiast from Zimbabwe 🇿🇼 who loves creating innovative solutions. Check out his portfolio at craigeex.vercel.app!\n\n*🛑 To stop AI mode:* Type .ciara_stop\n\nLet's chat! Ask me anything! 🚀`;
            
            await sock.sendMessage(m.chat, {
                image: { url: 'https://files.catbox.moe/0bn6cs.jpg' },
                caption: welcomeText
            }, { quoted: m });
        } else {
            m.reply('🤖 CIARA-IV AI is already active! Use .ciara_stop to disable.');
        }
    }
};

// Stop CIARA AI
export const ciara_stop = {
    name: 'ciara_stop',
    category: 'ai',
    description: 'Disable CIARA AI auto-responses',
    execute: async (sock, m) => {
        if (global.db.settings.aimode) {
            global.db.settings.aimode = false;
            m.reply('🤖 CIARA-IV AI has been deactivated. Use .ciara_ai to enable again.');
        } else {
            m.reply('❌ CIARA-IV AI is already inactive.');
        }
    }
};

// Image generation command with DALL-E
export const imagine = {
    name: 'imagine',
    aliases: ['generate', 'create'],
    category: 'ai',
    description: 'Generate images with AI',
    execute: async (sock, m, args) => {
        if (!args[0]) return m.reply('❌ Please provide an image description!\n\nExample: .imagine a futuristic city at sunset');
        
        try {
            const description = args.join(' ');
            m.reply('🎨 AI is creating your image...');
            
            const imageUrl = await generateImage(description);
            
            await sock.sendMessage(m.chat, {
                image: { url: imageUrl },
                caption: `*🎨 AI GENERATED IMAGE*\n\n📝 *Description:* ${description}\n🤖 *Generated by:* CIARA-IV AI\n👨‍💻 *Created by:* CraigeeX🫟\n\n✨ _Image created using DALL-E AI technology_`
            }, { quoted: m });
            
        } catch (error) {
            console.error('Image Generation Error:', error.response?.data || error.message);
            m.reply('❌ Image generation failed. Please try again with a different description.');
        }
    }
};

// Text summarization
export const summary = {
    name: 'summary',
    aliases: ['summarize', 'tldr'],
    category: 'ai',
    description: 'Summarize text using AI',
    execute: async (sock, m, args) => {
        if (!args[0] && !m.quoted) return m.reply('❌ Please provide text to summarize!\n\nExample: .summary [long text] or reply to a message');
        
        try {
            const text = args.join(' ') || m.quoted?.text || '';
            if (text.length < 50) return m.reply('❌ Text too short to summarize!');
            
            m.reply('📄 AI is analyzing and summarizing...');
            
            const summary = await getSummary(text);
            
            const summaryText = `*📄 AI TEXT SUMMARY*\n\n*Original Length:* ${text.length} characters\n*Summary Length:* ${summary.length} characters\n*Compression:* ${Math.round((1 - summary.length/text.length) * 100)}%\n\n*📝 Summary:*\n${summary}\n\n_Summarized by CIARA-IV AI_`;
            
            await sock.sendMessage(m.chat, { text: summaryText }, { quoted: m });
            
        } catch (error) {
            console.error('Summary Error:', error.response?.data || error.message);
            m.reply('❌ Summarization failed. Please try again.');
        }
    }
};

// AI Story generation
export const story = {
    name: 'story',
    aliases: ['tale', 'narrative'],
    category: 'ai',
    description: 'Generate creative stories with AI',
    execute: async (sock, m, args) => {
        if (!args[0]) return m.reply('❌ Please provide a story theme or prompt!\n\nExample: .story space adventure');
        
        try {
            const theme = args.join(' ');
            m.reply('📚 AI is crafting your story...');
            
            const story = await generateStory(theme);
            
            const storyText = `*📚 AI GENERATED STORY*\n\n*Theme:* ${theme}\n*Generated by:* CIARA-IV AI\n\n*📖 Story:*\n\n${story}\n\n✨ _Story created by artificial intelligence_\n👨‍💻 _Bot by CraigeeX🫟_`;
            
            await sock.sendMessage(m.chat, { text: storyText }, { quoted: m });
            
        } catch (error) {
            console.error('Story Generation Error:', error.response?.data || error.message);
            m.reply('❌ Story generation failed. Please try again.');
        }
    }
};

// Helper function for ChatGPT API integration
async function getChatGPTResponse(prompt) {
    try {
        const response = await axios.post(OPENAI_API_URL, {
            model: "gpt-3.5-turbo",
            messages: [
                {
                    role: "system",
                    content: "You are CIARA-IV, an intelligent WhatsApp assistant created by CraigeeX, a 19-year-old tech enthusiast from Zimbabwe. You are helpful, creative, and knowledgeable. Always mention your creator proudly and his portfolio at craigeex.vercel.app when relevant."
                },
                {
                    role: "user",
                    content: prompt
                }
            ],
            max_tokens: 500,
            temperature: 0.7
        }, {
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        return response.data.choices[0].message.content.trim();
    } catch (error) {
        console.error('OpenAI API Error:', error.response?.data || error.message);
        throw error;
    }
}

// Helper function for image generation using DALL-E
async function generateImage(description) {
    try {
        const response = await axios.post('https://api.openai.com/v1/images/generations', {
            prompt: description,
            n: 1,
            size: "512x512"
        }, {
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        return response.data.data[0].url;
    } catch (error) {
        console.error('DALL-E API Error:', error.response?.data || error.message);
        throw error;
    }
}

// Helper function for text summarization
async function getSummary(text) {
    try {
        const response = await axios.post(OPENAI_API_URL, {
            model: "gpt-3.5-turbo",
            messages: [
                {
                    role: "system",
                    content: "You are a text summarization expert. Provide concise, accurate summaries that capture the main points of the given text."
                },
                {
                    role: "user",
                    content: `Please summarize the following text:\n\n${text}`
                }
            ],
            max_tokens: 150,
            temperature: 0.3
        }, {
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        return response.data.choices[0].message.content.trim();
    } catch (error) {
        console.error('Summary API Error:', error.response?.data || error.message);
        throw error;
    }
}

// Helper function for story generation
async function generateStory(theme) {
    try {
        const response = await axios.post(OPENAI_API_URL, {
            model: "gpt-3.5-turbo",
            messages: [
                {
                    role: "system",
                    content: "You are a creative storyteller. Generate engaging, imaginative stories based on the given themes. Keep stories appropriate for all audiences and around 200-300 words."
                },
                {
                    role: "user",
                    content: `Write a creative story about: ${theme}`
                }
            ],
            max_tokens: 400,
            temperature: 0.8
        }, {
            headers: {
                'Authorization': `Bearer ${OPENAI_API_KEY}`,
                'Content-Type': 'application/json'
            }
        });

        return response.data.choices[0].message.content.trim();
    } catch (error) {
        console.error('Story API Error:', error.response?.data || error.message);
        throw error;
    }
}